services:
    mongo:
        image: mongo:7
        container_name: practica-mongo
        restart: unless-stopped
        volumes:
        - mongo-data:/data/db
        networks:
        - practica-network

    nginx:
        build:
        context: .
        dockerfile: nginx/Dockerfile
        container_name: practica-nginx
        restart: unless-stopped
        ports:
        - "8080:80"
        networks:
        - practica-network

    api:
        build: ./api
        container_name: practica-api
        restart: unless-stopped
        ports:
        - "3000:3000"
        env_file:
        - .env
        depends_on:
        - mongo
        - nginx
        networks:
        - practica-network

volumes:
    mongo-data:

networks:
    practica-network:
        driver: bridge